### PR TITLE
Fix case on plugins directory

### PR DESCRIPTION
**Pull request by mloberg**
When trying to use anything from the _Plugins_ namespace, I would get an error from composer about not matching the expected filename. This fixes that issue by making sure the case matches.

### CODE REVIEW

**Comment by mloberg** [comment]
@roippi Any changes you'd like me to make or can we get this merged in?

**Comment by irudoy** [comment]
@andrewrota maybe you can help?

**Comment by duivvv** [comment]
🙏

**Comment by davidkmenta** [comment]
Merge please 🙏

**Pull request merged**
